# SPDX-License-Identifier: GPL-2.0

START := 0x80000000

ELF_ARCH := aarch64
ELF_FORMAT := elf64-littleaarch64

KBUILD_CFLAGS += -mgeneral-regs-only

KBUILD_LDFLAGS += -maarch64elf

include $(srctree)/arch/arm64/Makefile.cpu
